### ISSUE TITLE
Nested calc() not working (breaks in Safari)

### ISSUE THREAD

**Issue by teddybradford** [Khan/aphrodite#101]
Writing a style like this:

`flex-basis: "calc(100% * 1 / 3 - ((1.5rem * 3) - ((1.5rem * 3) * 1 / 3)))"`

produces this:

`flex-basis: calc(100% * 1 / 3 - (calc(1.5rem * 3) - (calc(1.5rem * 3) * 1 / 3))) !important;`

which is invalid due to the extra calc() functions that are being inserted after compilation.

The calc() spec only allows for a single calc() function call surrounding all operations. Some browsers are still able to parse this invalid style code, but Safari doesn't even try to so the style is ignored.

**Comment by xymostech** [comment]
Hello @teddybradford What version of aphrodite are you using? Can you provide a more complete repro case? I'm not seeing this happening for me ([see this example output](https://output.jsbin.com/qoseye?code=%7B%0A%20%20%22red%22%3A%20%7B%0A%20%20%20%20%22flex-basis%22%3A%20%22calc%28100%25%20%2A%201%20%2F%203%20-%20%28%281.5rem%20%2A%203%29%20-%20%28%281.5rem%20%2A%203%29%20%2A%201%20%2F%203%29%29%29%22%0A%20%20%7D%0A%7D))

**Comment by teddybradford** [comment]
I figured out what is causing the issue; I was passing properties into a function that returned CSS properties, and one of variables I was passing into it had a calc() function in it, so the function was nested the calc() functions. Sorry about that!

**Comment by xymostech** [comment]
No problem, glad you found your solution.
