### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by tiborsaas** [Khan/aphrodite#103]
Hello,

A few example use cases would be great to add to the readme, because I struggle to find any.

**Comment by kentcdodds** [comment]
There's a folder in the repo for this. What's it missing? https://github.com/Khan/aphrodite/tree/master/examples

**Comment by tiborsaas** [comment]
Motivation behind using JS to generate inline CSS, why it is a good idea. It's not obvious at first and since it flies against all known best practice, you might want to clarify that to newcomers in the readme.

**Comment by kentcdodds** [comment]
We could add [CSS in JS](http://blog.vjeux.com/2014/javascript/react-css-in-js-nationjs.html) to the top of the README. AFAIK, that's what kicked off this CSS in JS "movement"

**Comment by lencioni** [comment]
Thanks for opening this issue! I'd be happy to review a PR that adds examples to the readme!
