### ISSUE TITLE
FUOC in Safari normal?

### ISSUE THREAD

**Issue by theotow** [Khan/aphrodite#106]
Hi,

i just got started with aphrodite, and i just discovered that in safari 9.1.1 i get pretty bad  FUOC, not all the time but if you press cmd + r like 5 times in a row. In Chrome it seems to be fine. 

I dont use SSR just FYI

i tried to wrap the render in 

```
setTimeout(() => {
    render(<Root />, document.getElementById('app'))
  }, 0)
```

with minor effect on the  FUOC. 

Same problem when compiled in 'prod' mode

Just checked the https://javascriptair.com/ page, seems like SSR is the online way to to get this straight in safari.

Does anyone have a clue on this? 😅😅

**Comment by kentcdodds** [comment]
Sorry, what is FOC?

**Comment by jlfwong** [comment]
Hi @theotow, sorry you're running intro troubles!

I'm assuming you meant FUOC? Flash of unstyled content?

That `setTimeout` is certainly not going to help at all. If there's a FUOC, it would be *between* the DOM insertion and the CSS generation.

If this is a problem in Safari, then SSR will only help with the initial render -- it won't help with subsequent mutations that rely on styles that aren't already on the page (i.e. rendering an overlay that uses styles not using styles used by anything else).

Do you have a page you've been able to reproduce consistently on that you can link to?

I'm unsure of what you're reference on javascriptair.com

**Comment by kentcdodds** [comment]
> I'm unsure of what you're reference on javascriptair.com

For context, JavaScriptAir.com is the site that I'm using aphrodite heavily on. It's using SSR (technically, it's generated on travis and static HTML files are deployed to a server, but ... splitting hairs) so it doesn't have this problem. I think that's what @theotow was saying 😄

**Comment by theotow** [comment]
@jlfwong thanks for the info, yes indeed i mean FUOC, i cannot disclose the code :( But it should be fairly easy to reproduce. Just dont SSR the page and open it in Safari and refresh. 

I just resolved the issue with 
```
<div style={{'display': 'none'}} className={css(styles.root)}>
        <IntlProvider locale='en' defaultLocale='en' messages={null}>
          <Router history={hashHistory} routes={Routes} />
        </IntlProvider>
        {DevToolsInclude()}
      </div>
``` 

maybe it worth mentioning this in the docs if other users also have the issue, i mean 'hey' not everyone does SSR

Im using  ```new ExtractTextPlugin('[name].css')``` with webpack in the dev env in addition to aphrodite

@kentcdodds yeah you are safe, you made me try aphrodite with your swarming. So far its awesome, the css is so much more clean because aphrodite does not allow any nesting + no switching between files

**Comment by kentcdodds** [comment]
Hmmm... I'm inclined to believe that the cause of the issue you're experiencing is not aphrodite. Do you mind reproducing the issue in an isolated environment like JSBin? (You can clone [this one](https://jsbin.com/kenuvep/edit?js,output))

**Comment by theotow** [comment]
@kentcdodds thanks for the demo link, that one works well in safari, can somehow not reproduce it, will close this for now.
