### ISSUE TITLE
Use insertRule instead of appendChild in production

### ISSUE THREAD

**Issue by kentcdodds** [Khan/aphrodite#115]
So check [this](https://twitter.com/threepointone/status/758095395482324992) out:

<img width="642" alt="screen shot 2016-07-26 at 8 28 11 pm" src="https://cloud.githubusercontent.com/assets/1500684/17162037/83503d58-536f-11e6-908a-821de51d6df3.png">

Based on @threepointone's experience, I suggest that we explore the possibility of doing this. Mostly because of [this](https://twitter.com/threepointone/status/758126742825426944): 

<img width="638" alt="screen shot 2016-07-26 at 8 30 44 pm" src="https://cloud.githubusercontent.com/assets/1500684/17162074/da59832a-536f-11e6-9426-a41ec029c6fc.png">

Thoughts? 💭

**Comment by jlfwong** [comment]
Perhaps see #83?

**Comment by kentcdodds** [comment]
Ah! That's right, totally forgot about that PR 👍  cc @threepointone, see #83

**Comment by kentcdodds** [comment]
Closing as this is already tracked in #76

**Comment by threepointone** [comment]
Don't forget the tradeoff, you wouldn't want to use this in dev. Cheers all!

**Comment by xymostech** [comment]
@threepointone What do you mean when you say that the styles aren't editable? Like, you can't edit them in the style inspector, or you can't edit the contents of the style sheet?

**Comment by threepointone** [comment]
The former; this is the main caveat with this method. https://bugs.chromium.org/p/chromium/issues/detail?id=387952#c6

**Comment by threepointone** [comment]
Dunno if you folks have made any progress on this, but thought this might help. I extracted just the 'stylesheet' parts of glamor into a [generic module](https://github.com/threepointone/glamor/blob/master/src/sheet.js). It handles using `appendChild` in dev vs `insertRule` in production (if available), uses multiple backing tags to expand rule space, and also has a server side 'shim'. I've tested it fairly throughly for both bugs and perf, and I like it so far. Please feel free to `import { StyleSheet } from 'glamor/lib/sheet'`, and / or copy paste and modify for your own purposes. Cheers!
