### ISSUE TITLE
Unit testing without a DOM

### ISSUE THREAD

**Issue by danprince** [Khan/aphrodite#119]
Trying Aphrodite out on a new project and authoring styled components has been great so far. Just started writing the next round of unit tests and I've come up against problems.

Just to give you an idea of how these tests look:

```js
import { shallow } from 'enzyme';
import { css } from 'aphrodite';

let wrapper = shallow(<MyComponent />);
assert.ok(
  wrapper.find('button').hasClass(css(MyComponent.styles.selected)),
  'button should have selected styles applied'
);
```

The calls to `css()` ultimately call `injectStyleTag` which requires the `document` object to be present, which isn't an issue when running tests with a headless browser / jsdom, but it prevents anyone from running lightweight shallow render tests under plain old node.

I've tried to bootstrap with [undom][1] and [react-faux-dom][2] but neither expose a `document` object in a way that works with Aphrodite -- undom doesn't support `querySelector` and react-faux-dom exposes the required methods over multiple objects.

Would it be possible to just stay hands off the DOM if the `document` object doesn't exist in scope? It'd be handy to be able to get the class name back for testing, so how about adding another top level method that works like `injectAndGetClassName`, but doesn't perform the injection step and just returns the class name.

In theory, nothing would change at the client side, but the `css` function would need to be revamped to something like this.

```js
const css = (...styleDefinitions) => {
    const useImportant = true;   // Append !important to all style definitions
    if(typeof document === 'object') {
      return injectAndGetClassName(useImportant, styleDefinitions);
    } else {
      return getClassName(useImportant, styleDefinitions);
    }
};
```

Happy to put a PR together if this makes sense for you guys!

[1]: https://github.com/developit/undom
[2]: https://github.com/Olical/react-faux-dom

**Comment by jlfwong** [comment]
Hi @danprince!

Our own tests work with [jsdom](https://github.com/tmpvar/jsdom), like you can see here: https://github.com/Khan/aphrodite/blob/master/tests/inject_test.js

But if you'd like to just ignore the styles, then you can disable style injection into the DOM with `StyleSheetTestUtils.suppressStyleInjection`, as implemented in #91, in response to #90.

Does that answer your question?

It looks like there's no documentation around that function in the README right now -- I'd be happy to accept a PR for that :)

**Comment by danprince** [comment]
Thanks @jlfwong! Using the suppression technique will work fine for now, but even with some docs for `StyleSheetUtils`, wouldn't it be easier and generally less surprising for users if aphrodite "just works" in both contexts? It'd certainly make it a bit friendlier for people coming here with tests that use shallow rendering.

**Comment by jlfwong** [comment]
I can see the benefit of having this work automatically for newcomers, but prefer to err on the side of being explicit.

The example modification you provided to the `css` function would break server-side rendering, where there may be no `document` object by design.

I'm not a huge fan of trying to guess what the user wanted based on the environment, since there always ends up being use cases that are difficult to anticipate.

For instance, it's possible you want to run the tests in the console (where there is no `document`) *and* in the browser (where there is). You'd want the behaviour to be the same regardless of the test environment.
