### ISSUE TITLE
How to assign a class conditionally?

### ISSUE THREAD

**Issue by joannakrk** [Khan/aphrodite#14]
I'd like to be able to use some variable (let's say 'ok') to decide on the styling of an element:
`<div className={ok ? css(styles.activeButton, styles.okButton) : css(styles.okButton)}>OK</div>`

Is there any better way to do it? (e.g. a way to pass along pairs of class names and booleans to css method?)

**Comment by xymostech** [comment]
You can move the `ok` variable inside of the call to `css()`. `css()` will ignore any falsey values in its arguments. So your example would turn into `<div className={css(ok && styles.activeButton, styles.okButton)}>OK</div>`.

Also remember that later arguments override earlier arguments, so `styles.activeButton` should probably go after `styles.okButton` if they have overlapping styles.

**Comment by joannakrk** [comment]
Thanks Emily! Do you think it'd be possible to add it to the documentation? It's a useful feature:)
