### ISSUE TITLE
What changed in 1.0?

### ISSUE THREAD

**Issue by jampy** [Khan/aphrodite#165]
Version 1.0 has been released a few days ago. 

What has changed since 0.6, since changing the major version number usually implies breaking changes?

**Comment by jlfwong** [comment]
Hi @jampy,

Just added a Changelog: https://github.com/Khan/aphrodite#changelog

Should've added it a long time ago -- hope that helps!

It's likely not a breaking change, but more a signal that we now believe Aphrodite is stable and roughly feature complete. The semantics of semver aren't intended to work quite the same way for versions <= 1.0

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
> http://semver.org/
