### ISSUE TITLE
Media Query Set

### ISSUE THREAD

**Issue by natew** [Khan/aphrodite#166]
Proposal for allowing defining media queries on the top level of the object passed into StyleSheet, which would allow for a much simpler syntax when changing multiple elements.

Similar to docs this could be written:

```js
const styles = StyleSheet.create({
    red: {
        backgroundColor: 'red'
    },

    blue: {
        backgroundColor: 'blue'
    },

    hover: {
        ':hover': {
            backgroundColor: 'red'
        }
    },

    '@media (max-width: 600px)': {
        small: {
            backgroundColor: 'red'
        },
        blue: {
           fontSize: '24px'
        }
    }
})
```

**Comment by jlfwong** [comment]
Hi @natew!

What merging semantics would you propose? What happens if you define `small` in the top-most `StyleSheet.create`? What if that key *also* had an `@media` key. Which takes precedence?

The reason we have everything nested below the top-most keys at the moment is that it makes merging semantics much clearer.

**Comment by natew** [comment]
Hm, perhaps this is something more for my own library. We've written a set of helpers and standards on top of aphrodite:

https://github.com/motion/motion/tree/master/packages/gloss

I could perhaps make themes take media queries and convert them. We already do some fairly complex merge logic. For example you can:

```
static style = {
   item: { color: 'red', background: 'black' },
}

static theme = {
  dark: {
    item: { color: 'darkred' },
  }
}
```

Which will pick up the darkred and merge with the background

**Comment by jlfwong** [comment]
@natew I really like that, at the moment, the logic of precedence is just a deep merge with no more rules than that. I'm going to close this, but hope you wind up being able to get the syntax you want with gloss :)
