### ISSUE TITLE
css([]) breaks with an error

### ISSUE THREAD

**Issue by Nek** [Khan/aphrodite#168]
I stumbled upon this while trying to merge several styles and narrowed it to just:
```css([])```
This gives me:
```generate.js?28d6*************:68 Uncaught (in promise) TypeError: Cannot convert undefined or null to object```

Right now I'm using a workaround checking a length of an array when I pass it to css().
Probably this should be handled by css() itself.

**Comment by xymostech** [comment]
Hello @Nek!

Can I ask what version of Aphrodite you're using? Up until recently, we only supported passing styles as arguments to `css()`, not arrays of styles. `css([])` doesn't fail for me on the latest version.

**Comment by Nek** [comment]
Sorry for not mentioning it. I'm AFK right now. Will report it tomorrow.

**Comment by Nek** [comment]
This one can be closed. 
I was on a version number less than 1.0. 
1.0 works fine.

**Comment by xymostech** [comment]
Great!
