### ISSUE TITLE
Promise support for renderStatic

### ISSUE THREAD

**Issue by vlasenko** [Khan/aphrodite#169]
Hi there,

Thank you for the awesome stylesheet library. 

I saw this discussion here and I would like to give it a thought again by bringing new use cases to your attention:
https://github.com/Khan/aphrodite/pull/132

I would like to raise the point that supporting callback returning `Promise` might be the legitimate case when using `StyleSheetServer.renderStatic`. For example one has this case if it uses server-side rendering with ApolloStack:
https://github.com/apollostack/react-docs/blob/master/source/server-side-rendering.md#user-content-getDataFromTree

Right now to support both ApolloStack server-side rendering and Aphrodite styles one have to use hacks like this:
https://github.com/sysgears/apollo-fullstack-starter-kit/commit/b7db7c6b550026149cec4734d12291456b4b190e

Thanks,
Victor

**Comment by xymostech** [comment]
Hello! Sorry for not looking in to this earlier. I responded to #132 now, hopefully we can figure this out. :)
