### ISSUE TITLE
Cannot generate className include '$ '

### ISSUE THREAD

**Issue by heineiuo** [Khan/aphrodite#178]
```
const styles = StyleSheet.create({
  foo$$bar: {
    color: 'red'
  }
})
```

this class will not be generated

**Comment by heineiuo** [comment]
ok. i found $ is illegal in CSS grammer:(

**Comment by xymostech** [comment]
:P Maybe we could do some sort of filtering or throw an error, but it probably makes sense for you to just fix your code.
