### ISSUE TITLE
[Bug] Pseudo Elements Content Blank

### ISSUE THREAD

**Issue by patrickml** [Khan/aphrodite#180]
in order to create a blank content value for a pseudo-element you must escape the quotes. It should be expected that if the content is blank then the value is `''` not requiring `\'\'`

Example
```js
selectorLabel: {
    width: '176px',
    justifyContent: 'center',
    display: 'flex',
    position: 'relative',
    ':before': {
      content: '\'\'',
      height: '45px',
      position: 'absolute',
      left: 0,
      right: 0,
      top: '-24px',
      margin: 'auto',
      width: '1px',
      background: 'rgb(224, 224, 224)',
    },
```

**Comment by danhayden** [comment]
not really a bug, plus this is explained in the readme https://github.com/Khan/aphrodite#assigning-a-string-to-a-content-property-for-a-pseudo-element

**Comment by patrickml** [comment]
@danhayden fair enough, thank you.
