### ISSUE TITLE
can i use this like`style={styles.btn}`?

### ISSUE THREAD

**Issue by heineiuo** [Khan/aphrodite#183]
I found `styles.btn` has a property `_definition`, so i can use `style={styles.btn._definition}`, but it looks not cool. :(

**Comment by jlfwong** [comment]
Hi @heineiuo. The `_` prefixes are meant to indicate that a field is private to the library, meaning they should be used outside of the library itself.

If you want to be able to use something as either inline styles or via Aphrodite, you can accomplish that like so:

```js
const btn = {
    fontSize: '72px'
};
const styles = StyleSheet.create({
    btn: btn
});

// Use via Aphrodite
const Button = () => <button class={css(styles.btn)}>Hello!</button>;
const OtherButton = () => <button style={btn}>Hello again!</button>;
```

Does that answer your question?
