### ISSUE TITLE
Aphrodite logo

### ISSUE THREAD

**Issue by thiamsantos** [Khan/aphrodite#217]
Would be great if the project had a nice logo.

**Comment by xymostech** [comment]
It's funny that you bring that up! I just landed a change to http://khan.github.io/ which adds Aphrodite to the list and includes a logo... it's pretty stylized so maybe it's not what we want overall, but it is a logo.

(direct link to the logo: http://khan.github.io/img/aphrodite.svg)

**Comment by thiamsantos** [comment]
Cool @xymostech! Maybe you could include this logo on readme.

**Comment by thiamsantos** [comment]
Maybe the logo could have a transparent background to fit better on the readme.
