### ISSUE TITLE
Integrate with coveralls

### ISSUE THREAD

**Issue by thiamsantos** [Khan/aphrodite#218]
Integrate the project with [coveralls](https://coveralls.io/) to add a fancy badge in the readme, like this one from lodash:

[![Coverage Status](https://coveralls.io/repos/github/lodash/lodash/badge.svg?branch=master)](https://coveralls.io/github/lodash/lodash?branch=master)

And the setup is pretty simple:

1. Create an account with your github at the website.
2. Add this repo on the website:

![screenshot coveralls](https://cloud.githubusercontent.com/assets/13632762/23812643/260a370e-05ba-11e7-9377-8199d4e56f40.png)

3.  Add a simple script to the `package.json`:
```js
"coveralls": "npm run coverage && nyc report --reporter=text-lcov | coveralls"
```
4. And run this script with [travis](https://travis-ci.org/), just adding this snippet below to the end of `travis.yml`
```yml
after_script:
  - npm i -g coveralls
  - npm run coveralls
```

**Comment by xymostech** [comment]
Looks cool @thiamsantos! I can get to this at some point, but if you (or someone else) makes a PR I'd be happy to integrate that. :)

**Comment by thiamsantos** [comment]
Nice @xymostech! I'll be happy to send a PR, but the first two steps that I mentioned above need to be made by a owner/collaborator of the project, someone that has write access.

**Comment by xymostech** [comment]
@thiamsantos okay, I did the first two steps! I don't think I need to add any env variables to travis or anything, so you should be set to send the PR. :)

**Comment by thiamsantos** [comment]
@xymostech thanks! In a few minutes I'll send the PR.
