### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by thiamsantos** [Khan/aphrodite#221]
Would be great update the readme following the [standard readme](https://github.com/richardlitt/standard-readme) [specification](https://github.com/RichardLitt/standard-readme/blob/master/spec.md). In order to provide a predictable format for facilitate the reading. And seize the opportunity to add an explanation of [why use this project and the CSS in JS technique](https://github.com/Khan/aphrodite/issues/103#issuecomment-233389840).

**Comment by lencioni** [comment]
I'm going to close this as a duplicate of #103. Please feel free to add to the discussion over there or open a PR.
