### ISSUE TITLE
runkit example no longer working

### ISSUE THREAD

**Issue by xymostech** [Khan/aphrodite#222]
I previously added a runkit example to aphrodite by adding a file and referencing it in the package.json: https://github.com/Khan/aphrodite/blob/master/package.json#L70

It looks like that example no longer works (https://runkit.com/npm/aphrodite). I thought maybe because of the rename (they used to be called "tonic") the property in package.json should be switched to `runkitExampleFilename` but there are several projects with that (e.g. https://github.com/SplittyDev/evee.js/blob/master/package.json#L44) that also don't have examples (https://runkit.com/npm/evee). I can't find the documentation on how to add an example any more (here's the old documentation for when it was called tonic https://tonicdev.uservoice.com/knowledgebase/articles/765846-how-do-i-customize-the-example-for-my-npm-package)

**Comment by lencioni** [comment]
Here's what I see right now when I click on Run:

<img width="687" alt="screen shot 2017-05-10 at 7 55 03 am" src="https://cloud.githubusercontent.com/assets/195534/25905129/0194a302-3556-11e7-8745-c978d746f2fe.png">

So, maybe this is working again? I'm going to close this issue, but please re-open it if it is still broken.
