### ISSUE TITLE
Question: How to use StyleSheet.rehydrate in a templated setup?

### ISSUE THREAD

**Issue by probedb** [Khan/aphrodite#223]
Hi,

We're using React/Redux with whiskers for templating. We also combine and minify our JS which is then used in the template.

How do I run StyleSheet.rehydrate in this template? Since StyleSheet doesn't exist, any JS has been minified.

I've managed to get everything else working including tests and StyleSheetServer.renderStatic works fine and the app starts without any issues.

This is the code where we generate the template. The important bits being the extraCss, content, and cssContent. The minified js/css is in jsBundle and cssBundle.

```
    const page = renderTemplate({
      production: !isDev(),
      content: html,
      cssContent: css.content,
      extraCss: JSON.stringify(css.renderedClassNames),
      canonicalPath: constructCanonicalPath(params.baseUrl, params.path),
      title: pageMetadata.title,
      description: pageMetadata.description,
      stores: JSON.stringify(serialiseStores(state)),
      jsBundle: config.assetPaths.js,
      cssBundle: config.assetPaths.css,
      newRelicHeader: newRelic && newRelic.getBrowserTimingHeader(),
    });
```

Many thanks,

**Comment by xymostech** [comment]
@probedb I'm not sure that I completely understand the problem that you're having, but I think you want to do something like this:

1. In your template, add a `<style>` tag like

   ```html
   <style data-aphrodite>{cssContent}</style>
   ```

2. Also in your template, before you include your js bundle, add a `<script>` tag like

   ```html
   <script>
   window.APHRODITE_REHYDRATE_DATA = {extraCss};
   </script>
   ```

3. In the index file of your javascript that gets bundled together, run something like

   ```js
   const {StyleSheet} = require("aphrodite");
   if (window.APHRODITE_REHYDRATE_DATA) {
       StyleSheet.rehydrate(window.APHRODITE_REHYDRATE_DATA);
   }
   ```

Does that make sense?

**Comment by probedb** [comment]
Cheers, I'll give it a go when I get into work tomorrow and let you know :) It's step 3 I'll have to figure out how to do. I think we're using webpack so will figure out how to keep a chuck of JavaScript from getting minified.

**Comment by xymostech** [comment]
@probedb Part 3 can be minified! As long as it's still referencing `window.APHRODITE_REHYDRATE_DATA` then it'll be fine. :)

**Comment by xymostech** [comment]
(and I'm going to close this issue because this isn't a problem with Aphrodite, and I think that will resolve your problem. Feel free to comment or re-open if you're still having trouble!)

**Comment by probedb** [comment]
Works as far as I can tell, thanks folks :)
