### ISSUE TITLE
Uncaught TypeError: StyleSheet.rehydrate is not a function

### ISSUE THREAD

**Issue by ferdinandsalis** [Khan/aphrodite#24]
Trying to get server-side rendering going with aphrodite. I am getting the following error, `Uncaught TypeError: StyleSheet.rehydrate is not a function`. Isn’t it assuming that this is a global? How would I make it available to the client?

Here is what I am doing. Am I missing something?
```js
import React, { Component, PropTypes } from 'react';
import serialize from 'serialize-javascript';

export default class Body extends Component {
  static propTypes = {
    assets: PropTypes.object,
    css: PropTypes.object,
    component: PropTypes.node,
    store: PropTypes.object
  };

  render() {
    const {css, html, assets, store} = this.props;

    return (
      <body>
        <div id="content" dangerouslySetInnerHTML={{ __html: html }}/>
        <script dangerouslySetInnerHTML={{ __html: `StyleSheet.rehydrate(${JSON.stringify(css.renderedClassNames)});`}} />
        <script dangerouslySetInnerHTML={{ __html: `window.__data=${serialize(store.getState())};` }} charSet="UTF-8"/>
        {Object.keys(assets.javascript).map((asset, key) =>
          <script src={assets.javascript[asset]} key={key} charSet="UTF-8"/>
        )}
      </body>
    );
  }
}
```
Thanks for your help.

**Comment by jlfwong** [comment]
Hi there!

If you wish to use the code as you have it listed here, you need to have Aphrodite load and set `window.StyleSheet` in a script that loads before the `StyleSheet.rehydrate` call.

In your example, the `StyleSheet.rehydrate` call is the very first JavaScript that executes, so it can't possibly have loaded aphrodite by then.

There's an example in this repository that has server-side rendering working for you to base your example off of: https://github.com/Khan/aphrodite/tree/master/examples

**Comment by ferdinandsalis** [comment]
Thanks for pointing me into the right direction.
