### ISSUE TITLE
Outline transition flickers

### ISSUE THREAD

**Issue by Soreine** [Khan/aphrodite#241]
Might be a bug.

I have the following style, that includes outline with transition property:

```js
const styles = StyleSheet.create({
    commentableHighlightable: {
        transitionProperty: 'background, outline',
        transitionDuration: '0.2s',
        background: 'transparent',
        outline: 'solid 6px transparent'
    },
    commentableHighlighted: {
        background: '#0f0',
        outline: 'solid 6px #0f0'
    }
});
```

I use it to apply an outline conditionally to some components. But on page load (probably linked to aphrodite CSS injection), the outlines of the affected component transition from black to transparent, instead of being transparent from the start. See below what happens at page reload, right after the components mount:

![outline](https://cloud.githubusercontent.com/assets/5644953/26317367/8a12833c-3f17-11e7-9094-512832bcbb82.gif)

When I instead apply this style using the `style` props from React, the problem disappears.

_if anyone has a jsfiddle template for aphrodite, I can try to reproduce the issue_

**Comment by xymostech** [comment]
Thanks for the report! Can you share some of the code of how you're using the styles (i.e. the calls to `css()`)

Are you using React? I use WebpackBin instead of jsfiddle to play around with React and Aphrodite, like here: https://www.webpackbin.com/bins/-KklQQPzW0vbEqg2Grv3

**Comment by Soreine** [comment]
Thank you :)
I actually can't reproduce it, it only happens in Chrome too... So I think it's not aphrodite's fault
