### ISSUE TITLE
Feature request: ability to disable or configure autoprefixing

### ISSUE THREAD

**Issue by callumlocke** [Khan/aphrodite#254]
If I'm writing an app that will only run in modern Chrome or Electron, I want to disable autoprefixing so it's easier to debug things in devtools.

For example, Aphrodite generates all this:
![image](https://user-images.githubusercontent.com/250617/27958919-1fd7a072-631d-11e7-8a05-654ffcae89ce.png)

But all I want is this:
![image](https://user-images.githubusercontent.com/250617/27958943-4021c90c-631d-11e7-8c9e-f745d998fbb2.png)

**Comment by lencioni** [comment]
I think this is a duplicate of #239. Please feel free to reopen if I am mistaken.
