### ISSUE TITLE
Fix misleading project description

### ISSUE THREAD

**Issue by danny-andrews** [Khan/aphrodite#259]
When you do a Google search for aphrodite, this is what you see.

![image](https://user-images.githubusercontent.com/14965732/28327932-80f6800e-6baa-11e7-9a14-ce9de4bef1a1.png)

I think the description "It's inline styles, but they work!" is poor for a two reasons:
1. It's not accurate. Aphrodite doesn't operate on inline styles at all. It takes in full-featured css and generates classnames from it.
1. It is a big red flag for people who have been burned using libraries like material-ui, which actually relies on inline-styles (which **don't work**). If I hadn't been recommended this library by someone I trusted in the industry, I would have completely written it off just from the description.

I think this is a great project, but I think a small change to the description could increase the user-base significantly!

**Comment by lencioni** [comment]
Thanks for starting the discussion on this! Do you have any suggestions for something better?

**Comment by danny-andrews** [comment]
Hmmmm...good question. :D "CSS-in-JS" seems to be the most common term to describe the approach in this library. So maybe including that in the description would clue people in to what this library is about. Also including whatever you think sets this library apart from other CSS-in-JS approaches. I think built-in support for server-side rendering and extracting critical css is pretty rad! https://medium.com/seek-blog/a-unified-styling-language-d0c208de2660#6de3

**Comment by xymostech** [comment]
Hello @danny-andrews. Thank you for bringing this up... we've had discussions about this in the past, but haven't come up with a good alternative, so I've never changed it! Back when we first started working on Aphrodite, there weren't many libraries around and being able to be used in our production environment (i.e. "work") so we thought we'd be cheeky with the description. Something more up-to-date and useful is probably due, though!

You're right, those things are probably what're important to people using Aphrodite. Maybe "A CSS-in-JS library with server-side rendering, browser prefixing, and minimal css"?

**Comment by danny-andrews** [comment]
> Maybe "A CSS-in-JS library with server-side rendering, browser prefixing, and minimal css"?

I think that's definitely on the right track! What do you mean by "minimal css," though?

**Comment by xymostech** [comment]
I guess I mean "only generates the minimal amount of CSS needed to render the page", but maybe that's not clear. Do you have an idea for how to convey the "extracting critical CSS/only generating needed CSS" concept in very few words?

**Comment by danny-andrews** [comment]
Maybe something like "Framework-agnostic CSS-in-JS with support for server-side rendering, browser prefixing, and critical css."

Words is hard. :p

**Comment by xymostech** [comment]
That mostly sounds good to me, but I don't think most people will know what "critical CSS" means. To me, "minimal css" or maybe "minimal generated css" is clearer. What do you think?

**Comment by danny-andrews** [comment]
Yeah, it's certainly a tradeoff. For people who know the term, they will immediately understand what understand what functionality is being referenced, but to people who don't, it won't be much of a draw.

Changing it to "critical css *generation*" would help, but "minimal generated css" is good as well.

**Comment by xymostech** [comment]
I'm going to go with "Framework-agnostic CSS-in-JS with support for server-side rendering, browser prefixing, and minimum CSS generation". Hopefully that'll be more accurate and useful than what we have now. :) Thanks for complaining!

**Comment by danny-andrews** [comment]
> Thanks for complaining!

Anytime. ;)
