### ISSUE TITLE
Get generated css as string

### ISSUE THREAD

**Issue by danwoodbury** [Khan/aphrodite#260]
Hi,

How would I get the styles that are generated? Generally this works flawlessly for me but I have an edge case where I need to get the generated css to pass into an iframe.

To put it into context, I am building a kind of site builder where the preview is rendered into an iFrame, currently I am just using `style={styles.container._definition}` on the elements but this does not work for hover states or media queries and to have a fully functional preview I obviously need these.

If I can use athrodite on this with its intended purposes of setting a `className` and then passing the rendered styles into the iframe it would be much much better, and my preview would work correctly obviously.

Thanks

**Comment by xymostech** [comment]
I think this is the same issue as #130. I'm still not really sure of a good solution to this. :P I presented a vague idea of something like `StyleSheet.renderInFrame(frame, () => { ... })` to tell Aphrodite which frame to render in, but no work has been done on that.

Closing in favor of #130
