### ISSUE TITLE
Using an object instead of `StyleSheet.create` causes `css` to throw difficult to trace error

### ISSUE THREAD

**Issue by canadaduane** [Khan/aphrodite#265]
This was my first experience using Aphrodite:

I tried switching from Radium to Aphrodite. In Radium, styles are expressed as follows:

```
const styles = {
  container: {
    fontSize: 'large',
  },
  // ... etc ...
};
```

I didn't notice at first that Aphrodite requires the use of `StyleSheet.create({})` in the definition of styles and rather than changing the styles, I started switching all of the `style={styles.xyz}` jsx attributes to `className={css(styles.xyz)}` attributes. What resulted was the following difficult to trace error message:

```
TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at Function.keys (preview.bundle.js:19097)
    at OrderedElements.addStyleType (preview.bundle.js:68070)
    at generateCSS (preview.bundle.js:67780)
    at injectStyleOnce (preview.bundle.js:68475)
    at injectAndGetClassName (preview.bundle.js:68570)
    at css (preview.bundle.js:68249)
    at SearchBar (preview.bundle.js:49733)
    at preview.bundle.js:28187
    at measureLifeCyclePerf (preview.bundle.js:27957)
```

I realize this is a type error (and we have tools for this!) but it was an unpleasant first introduction to an otherwise fine looking library.

**Comment by PaulBrunache** [comment]
I'm confused because it just seems like you didn't read the API initially

Are you suggesting the error should be better because this error actually does make sense?

**Comment by canadaduane** [comment]
Yes, an error message that better explains the dumb mistake I made would
have saved a lot of time, and I think others might benefit, too.

**Comment by PaulBrunache** [comment]
submit a pull

**Comment by canadaduane** [comment]
I will if I have time (but I don't right now).
