### ISSUE TITLE
Override classname by providing string or function

### ISSUE THREAD

**Issue by erikfox** [Khan/aphrodite#267]
### Current State
Currently the returned classnames are deterministic: https://github.com/Khan/aphrodite/blob/master/src/inject.js#L282
```js
    let className;
    if (process.env.NODE_ENV === 'production') {
        className = processedStyleDefinitions.classNameBits.length === 1 ?
            `_${processedStyleDefinitions.classNameBits[0]}` :
            `_${hashString(processedStyleDefinitions.classNameBits.join())}${
                getStyleDefinitionsLengthHash(styleDefinitions)}`;
    } else {
        className = processedStyleDefinitions.classNameBits.join("-o_O-");
    }
```

### Desired State
I would like there to be an option for me to pass a function or explicit string that would override this, letting me choose the classname for the styles being injected.

### Use Case
I would like to use either `StyleSheet` or `css()` to create reusable, global classes with semantic names of my choosing. It would be nice to be able to generate a CSS library of functional utility classes (like [Tachyons](http://tachyons.io/)) using nothing but JS.

**Comment by erikfox** [comment]
Actually, this request may fall out of the domain of Aphrodite, as it looks like Aphrodite focuses on developing multiple `<style>` injections rather than a global stylesheet?

Please let me know if the use case I describes falls out of the scope of intended usage.

**Comment by xymostech** [comment]
Hmm, we've talked about this before in #160 and I think the answer is that we want to have control over the class names that we generate and don't want people to depend on the output, so we don't want to let people change how they are generated.
