### ISSUE TITLE
consider exposing an API to allow custom browser support

### ISSUE THREAD

**Issue by cezaraugusto** [Khan/aphrodite#268]
The [browser-list](https://github.com/Khan/aphrodite/blob/master/tools/generate_prefixer_data.js#L8) could be configurable to allow authors to edit which browser they'd like to support. 

With the current built-in list, we end up with bloated styles that are often never used and makes debugging styles harder. In my case specifically I only need to support Chrome latest but I bet this is the kind of control authors may benefit from.

**Comment by lencioni** [comment]
I think this is a duplicate of #239. Please re-open if I am mistaken!
