### ISSUE TITLE
[TODO] important should add on attribute not global settings

### ISSUE THREAD

**Issue by LucasDvp** [Khan/aphrodite#269]
FYI.

**Comment by xymostech** [comment]
@LucasDvp Can you be more specific about what you're seeing here? I'm not sure what you mean.

**Comment by LucasDvp** [comment]
@xymostech It's more like the an enhancement, which mentioned on TODO list.
- adding the **"important!"** label to which attribute is set before, not all the attribute;

**Comment by xymostech** [comment]
We have the ability to not add `!important` to certain properties. By importing `"aphrodite/no-important"`, the generated styles won't have `!important` on them. I think that's what you're asking about, feel free to re-open this if that doesn't solve your problem.
