### ISSUE TITLE
How about mixin and nested items?

### ISSUE THREAD

**Issue by LucasDvp** [Khan/aphrodite#270]
How to set mixin and children's styles

**Comment by xymostech** [comment]
Hi @LucasDvp. Can you give some more specifics about what you're trying to accomplish?

I'm not sure if this is what you're asking about, but since Aphrodite styles are just Javascript objects, so you can do "mixins" by just merging styles:

```
const font = {
    fontFamily: "sans-serif",
    fontSize: 14,
    fontWeight: "bold",
};

const styles = StyleSheet.create({
    main: {
        ...font,
        marginLeft: 10,
    },
});
```

**Comment by LucasDvp** [comment]
@xymostech, like if I have React component

```html
<div className='parent'/{css(parent)}>
  <span>1</span>
  <span>2</span>
</div>
```

I need to style span,  so using css :

```css
/*children component*/
.parent > div {
  margin: '0 10px'
}
```

So if I'm using aphrodite, how do I style the children spans?

**Comment by xymostech** [comment]
Aphrodite doesn't currently let you do that. The current recommendation is to just manually add a class name to each of the spans. To make that easier, you can make a functional component, like:

```
const InnerSpan = props => <span {...props} className={css(styles.innerSpan)} />;

<div className={css(parent)}>
    <InnerSpan>1</InnerSpan>
    <InnerSpan>2</InnerSpan>
</div>
```

Functionality to do that is discussed in #10, but we don't have a good solution for that yet.

**Comment by LucasDvp** [comment]
I think nest is an crutial function, hope see it next version🤗
