### ISSUE TITLE
Class name minification breaks universal rendering when `NODE_ENV=production`

### ISSUE THREAD

**Issue by collingo** [Khan/aphrodite#272]
Unless I have set something up completely wrong it seems universal rendering of React based apps using Aphrodite is broken when `NODE_ENV=production`. This env var is not available in the browser so we get different classes generated on client/server and the following React error in the browser console...

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) y: 2 --><div class="body_144ob5i body_1n
 (server) y: 2 --><div class="_144ob5i _1nugvlx" d
```

Are there any workarounds that don't involve unsetting the commonly used `NODE_ENV` variable on production? Or have I set something up incorrectly to cause this?

**Comment by lencioni** [comment]
It sounds like you need to set up your build tools to replace the NODE_ENV properly. There are some instructions on how to do this here: https://facebook.github.io/react/docs/optimizing-performance.html

Does that help?

**Comment by collingo** [comment]
That'll do it! Thanks for the speedy response @lencioni 😄

**Comment by lencioni** [comment]
🐣
