### ISSUE TITLE
Bundle size badge

### ISSUE THREAD

**Issue by vladnicula** [Khan/aphrodite#278]
Styled components and glamorous have the bundle size and gziped size badge. 

I'm checking the bundle size differences now on my project. Would have been great if I saw it on the readme just like the other css in js frameworks.

**Comment by lencioni** [comment]
I think this is a great idea and this is related to something I've been thinking about doing here lately as well to reduce the bundle size impact of Aphrodite. Would you be interested in submitting a PR to add the badge?

**Comment by vladnicula** [comment]
https://github.com/Khan/aphrodite/pull/280

**Comment by lencioni** [comment]
Closed by #280
