### ISSUE TITLE
@font-face with system fonts

### ISSUE THREAD

**Issue by kilgarenone** [Khan/aphrodite#292]
What is the equivalent of this in aphrodite?

```
@font-face {
  font-family: system;
  font-style: normal;
  font-weight: 300;
  src: local(".SFNSText-Light"), local(".HelveticaNeueDeskInterface-Light"),
}
```
I tried the values as a string in quotes but didn't work.

**Comment by lencioni** [comment]
Can you share an example of the code you've tried and the result it has produced?
