### ISSUE TITLE
`minify` and `flushToStyleTag` missing from `no-important` export

### ISSUE THREAD

**Issue by Kerumen** [Khan/aphrodite#311]
If we use Aphrodite with the `no-important` import, we can't import `minify` and `flushToStyleTag`.

[default](https://github.com/Khan/aphrodite/blob/23e2d255341cb42102fc4451e8abcbc06842e9e7/src/index.js) vs [no-important](https://github.com/Khan/aphrodite/blob/23e2d255341cb42102fc4451e8abcbc06842e9e7/src/no-important.js) export

**Comment by lencioni** [comment]
Ah thanks for reporting! Would you be interested in submitting a PR that fixes this? (Bonus points for adding a test that verifies default and no-important always export the same stuff) 😸

**Comment by IagoLast** [comment]
should the typings should be updated too?
