### ISSUE TITLE
Edit generated styles in dev tools

### ISSUE THREAD

**Issue by Duskfall** [Khan/aphrodite#314]
Is there a way to edit the generated styles in chrome dev tools? Currently they are grayed out, which decreases development time.
![image](https://user-images.githubusercontent.com/2528125/37718701-ff9d49cc-2d2b-11e8-91ea-0f356a4a9403.png)

**Comment by dmiller9911** [comment]
Does a refresh help?  I sometimes see this if I have them open and things change.  Usually, a refresh will resolve it. I have seen this with other css-in-js libs before and never could pin down why it was doing it.

**Comment by jjmax75** [comment]
same here, can't turn off styles or edit in dev tools

**Comment by RetroBum** [comment]
Same problem here so swapped aphrodite for version 1.2.0 I had used in an old project where this worked.

**Comment by austenpayan** [comment]
I'm also experiencing this on Chrome and Safari. It seems to be Chrome/Webkit specific, as I can still edit the styles in Firefox.

**Comment by lencioni** [comment]
I think this is caused by the same thing as #321. More information in this comment: https://github.com/Khan/aphrodite/issues/321#issuecomment-396730606

**Comment by mbensch** [comment]
@lencioni This is likely caused by #240 since the `<style>` tag is no longer populated with the actual css rules.

**Comment by lencioni** [comment]
Indeed

**Comment by lencioni** [comment]
This has been fixed in Chrome 85: https://developers.google.com/web/updates/2020/06/devtools

**Comment by k-funk** [comment]
This is still a problem in Safari.
