### ISSUE TITLE
styles are not applied to child component until parent component gets mounted in react

### ISSUE THREAD

**Issue by vishnukumarbp** [Khan/aphrodite#324]
Hey mate,

i have tried to create a component which takes the applied css from parent component and update the font-size in child component according to that. 
I am assuming that, **there is an issue in the order of applying the styles.**

for the first time, when child's componentDidMount called, i have not got the styles applied to neither child or parent. so my child component does nothing on the styles.

Have created [sandbox](https://codesandbox.io/s/k2051pwl83) with explaning the issue. Please look into that,
question in [stackoverflow](https://stackoverflow.com/questions/50208911/child-component-need-to-be-called-after-parent-get-mounted-with-its-styles-in-re)

thanks,
vishnukumar

**Comment by vishnukumarbp** [comment]
Hey,

I found the answer, and it was mentioned in your doc also (which i completely missed), sorry for the inconvenience,. 

I have to use setTimeout in my Life cycle methods (componentDidUpdate, componentDidMount).

So you can close this ticket.,

thanks,

**Comment by jlfwong** [comment]
@vishnukumarbp Glad you were able to resolve the issue!
