### ISSUE TITLE
Server side rendering vs Aphrodite/no-important

### ISSUE THREAD

**Issue by istvanmakary** [Khan/aphrodite#353]
Hey!

First of all I want to tell, that I'm really satisfied with this module, I'm using it in several projects. 
I just want to highlight one really small, but annoying issue for my self and for other developers to avoid spending hours with it...
So if you are using `aphrodite/no-important` in your codebase, and you want render your site on the server don't forget to import { StyleSheetServer } from `aphrodite/no-important`!!! otherwise you gonna get this error: `Cannot automatically buffer without a document` maybe this is the solution for several issues reported to this module! 
I would like to ask the maintainers of this package to update the documentation!

Thanks,
Istvan

**Comment by csilvers** [comment]
Hi Istvan, I'm not a maintainer but I do have commit permissions on this repo, so I'd be happy to merge in a pull request if you'd like to make one!
