### ISSUE TITLE
How to generate class names without hash ?

### ISSUE THREAD

**Issue by golubvladimir** [Khan/aphrodite#377]
In documentation:
```
const styles = StyleSheet.create({
  foo: {
    color: 'red'
  },

  bar: {
    color: 'blue'
  }
});
```
Generate:
```
.foo_im3wl1 {
  color: red;
}
.bar_hxfs3d {
  color: blue;
}
```
I want:
```
.foo {
  color: red;
}
.bar {
  color: blue;
}
```
How to do it ?

**Comment by jlfwong** [comment]
Hi @golubvladimir,

There's intentionally no way to do this.

The hashes included in Aphrodite are fundamentally necessary for the design of Aphrodite to work correctly with server-side rendering and to avoid class name collisions between files.

So I think it's unlikely aphrodite will be updated with an option that allows the hashes to be removed entirely.
