### ISSUE TITLE
Styling with global classnames

### ISSUE THREAD

**Issue by jossmac** [Khan/aphrodite#52]
The use case for this is React Router's behaviour, where it appends the class `active` to the applicable element:
```jsx
<a class="aphroditeClassName_xyz123  active">Text</a>
```
Possible targeting syntax:
```js
aphroditeClassName: {
  color: 'black',

  '&.active': {
    color: 'red'
  }
}
```

**Comment by xymostech** [comment]
Aphrodite class names shouldn't interact with other external class names. Are you talking about the React Router `Link` component? It looks like it does concatenation to generate classes, which isn't going to work with Aphrodite. It shouldn't be too hard to make a version of `Link` that does work with Aphrodite: [AphroditeLink.jsx](https://gist.github.com/xymostech/51578b633c6a6238e137412064a6937a) which you'd use like:

```jsx
<AphroditeLink to={...} style={styles.link} activeStyle={styles.linkActive}>
    Text
</AphroditeLink>

const styles = StyleSheet.create({
    link: {
        color: "black",
    },

    linkActive: {
        color: "red",
    },
});
```

**Comment by acomito** [comment]
I'm dealing with this same issue. Thanks for posting the AphroditeLink. 

I guess the downside is you would have to make sure you keep your custom `<AphroditeLink />` up-to-date as react-router's link changes (although it seems to be more stable at the time I am writing this).
