### ISSUE TITLE
Can it effect page performance due to adding css styles while page is at client side ?

### ISSUE THREAD

**Issue by jpuri** [Khan/aphrodite#57]
Hi Team Aphrodite,

Thanks a lot for super nice work !
I have a query for you guys, Aphrodite will no doubt help to reduce bytes transferred for server side rendering, but can it effect page performance due to adding css styles while page is at client side ?

Thanks,
Jyoti

**Comment by b2whats** [comment]
I have a large application and don't see performance degradation

**Comment by jlfwong** [comment]
We've done work to optimize the time it takes to inject the CSS into the `<head>` when new styles are needed, and we avoid injecting CSS styles that have already been added to the `<head>`. It's in use in production at Khan Academy and as far as I know there hasn't been any major performance degradation.

The best thing you can do is to try it out, profile it yourself using Chrome Developer tools CPU profiling/timeline view, and judge for yourself. If you notice specific performance degradations that are reproducible, please feel free to post them as issues.

**Comment by jpuri** [comment]
Thanks @jlfwong , @b2whats
