### ISSUE TITLE
Question: does aphrodite use scoped stylesheets?

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/aphrodite#58]

**Comment by jlfwong** [comment]
You mean the `scope` attribute on the `<style>` tag? As described here? https://html.spec.whatwg.org/multipage/semantics.html#attr-style-scoped

Nope, not at the moment. Support is pretty limited (http://caniuse.com/#search=scoped), and I'm not sure what benefits it would buy us in Aphrodite given the nature of the generated classnames.

**Comment by kevinbarabash** [comment]
Cool.  The reason I was asking is because I'm looking into how well the CSS Animation API is supported and http://caniuse.com/#feat=css-animation mentions that `@keyframes not supported in an inline or scoped stylesheet in Firefox (bug 830056)`.  The bug report doesn't mention "inline" so I'm assuming that inline stylesheets and scoped stylesheets are the same thing.
