### ISSUE TITLE
Can't install npm package via JSPM

### ISSUE THREAD

**Issue by Palid** [Khan/aphrodite#59]
When trying to install aphrodite via JSPM it crashes not so nicely. It is possible to install package via github, however.
`$ jspm install npm:aphrodite`
```sh
     Updating registry cache...
     Downloading npm:aphrodite@0.2.0

warn Error on lookup for github:github:khan/inline-style-prefixer, retrying (1).
     Error: fatal: unable to access 'github:khan/inline-style-prefixer.git/': The
     requested URL returned error: 400


warn Error on lookup for github:github:khan/inline-style-prefixer, retrying (2).
     Error: fatal: unable to access 'github:khan/inline-style-prefixer.git/': The
     requested URL returned error: 400


warn Error on lookup for github:github:khan/inline-style-prefixer, retrying (3).
     Error: fatal: unable to access 'github:khan/inline-style-prefixer.git/': The
     requested URL returned error: 400


err  Error on lookup for github:github:khan/inline-style-prefixer
Error: fatal: unable to access 'github:khan/inline-style-prefixer.git/': The requested URL returned error: 400


err  Error looking up github:github:khan/inline-style-prefixer.

warn Installation changes not saved.
```

**Comment by Palid** [comment]
Installation via github won't work anyways due to wrong config in package.json - package.json links to lib/index.html, white it should link to src/index.html.

**Comment by xymostech** [comment]
Do you know why installing using npm fails with jspm? We only (officially) support npm right now.

**Comment by Palid** [comment]
Because you have screwed up configs in your package.json.

**Comment by xymostech** [comment]
I looked at your pull request, and like I said there, the files we upload to npm include files in the `lib/` directory, so the package is correct. Installing aphrodite from `npm` works perfectly fine, so there must be a problem with how jspm is getting its files from npm. (If it's trying to get the files from github despite there being an npm package, then that won't work because we don't support installing from github)

**Comment by xymostech** [comment]
I'm going to close this since I haven't heard back from you, and we don't plan to support jspm for now. If you have problems still feel free to re-open this.

**Comment by Palid** [comment]
@xymostech Some of the packages used for Aphrodite and Aphrodite itself have wrong entry point, which makes jspm not really compatible with it. I'll try having a bigger look into it when I have time, not much available in the nearest days.

**Comment by kentcdodds** [comment]
@Palid, please realize that Aphrodite does not have the wrong entry point. The main file is pointing to the generated CommonJS file... If you actually run `npm install aphrodite`, you'll see that all of the necessary files are there.
