### ISSUE TITLE
(Optionally) Use a singleton style tag to inject styles

### ISSUE THREAD

**Issue by zgotsch** [Khan/aphrodite#6]
IE9 will only use the first 31 `<style>` tags (https://support.microsoft.com/en-us/kb/262161). Since AFAICT Aphrodite creates a `<style>` tag for each class, it won't work on IE9 with a lot of components.

I don't know what the perf implications of this are, but I know that webpack's style-loader (https://github.com/webpack/style-loader) has an option for whether to use a single style tag or to use multiple.

**Comment by xymostech** [comment]
Woah. Didn't know that 31 tag limit was a thing! We could probably make an option to append to an existing <style> tag instead of making a new one each time.

**Comment by zgotsch** [comment]
Yeah, you can probably just create one with an id the first time and then `getElementById` subsequent injections.

**Comment by jlfwong** [comment]
It should probably just be the default behaviour unless it causes crazy perf problems. If it does cause crazy perf problems, we could maybe add 5 to the DOM, then repeatedly add to only the smallest of the 5 to prevent needing to reparse the larger blocks?

It would probably be good to land https://github.com/Khan/aphrodite/pull/1 too to help with this problem too.

**Comment by xymostech** [comment]
I looked into the perf implications of this, it looks like using more style tags is faster than appending to a style tag each time, but not appending to a style tag all the time is way better. I'm gonna look into this now.

**Comment by xymostech** [comment]
Oops, forgot to link to the jsperf: http://jsperf.com/append-to-style-vs-create-new-style
