### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by kentcdodds** [Khan/aphrodite#65]
I just upgraded to aphrodite@0.3.0 and stuff broke. I'll look into it further, but I thought that it'd be really nice to have a changelog.

I personally recommend automating this though the use of [semantic-release](http://npm.im/semantic-release).

**Comment by xymostech** [comment]
As discussed in #66, this instance was actually caused by one of our dependencies releasing a breaking change under a minor version bump. It would be nice to have changelogs though. Where do the changelogs from `semantic-release` go? In KaTeX we have changelogs in the releases: https://github.com/khan/KaTeX/releases

**Comment by kentcdodds** [comment]
Yes, that's where the changelog for semantic-release goes as well. Happens automatically based on the conventional commit message. Here's an example: https://github.com/kentcdodds/p-s/releases

[My (free) video course](http://kcd.im/write-oss) on writing open source libraries explains all of this. Starting around [here](https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-automating-releases-with-semantic-release?series=how-to-write-an-open-source-javascript-library).

I'm happy to help in any way I can :-)

**Comment by herrstucki** [comment]
I would also really appreciate if there was a changelog. It's really tedious to dig through commit messages (or worse: diffs) to figure out what's new and potentially breaking (and what was fixed). It doesn't have to be some elaborate automated setup in my opinion, just a Markdown file which is updated before the releases.

**Comment by lencioni** [comment]
I noticed that 1.0.0 was recently released. Is there somewhere I can look to see what the changes were so I know what to look for when updating?

**Comment by jlfwong** [comment]
https://github.com/Khan/aphrodite#changelog

Just added this. Didn't backfill it all the way since doing that is what prevented me from wanting to do that in the first place. So it's a start! If someone feels keen on backfilling, go for it!.

**Comment by lencioni** [comment]
Thanks @jlfwong! Perfect is the enemy of the good!
