### ISSUE TITLE
Transition properties not registering properly on mobile Safari

### ISSUE THREAD

**Issue by crm416** [Khan/aphrodite#68]
This may be a bug in the autoprefixer, but I'm having trouble getting CSS transitions to work with Aphrodite on mobile web (specifically, Safari on iOS 9.3.1).

<img width="274" alt="screen shot 2016-05-01 at 7 06 56 pm" src="https://cloud.githubusercontent.com/assets/1309177/14960852/94893460-104b-11e6-9e34-fcd36f27e977.png">

Notice that the unprefixed and vendor-prefixed `transition` properties are all cancelled out. (What's strange to me is that it's not rendering with any sort of warning or error; the UI seems to suggest that it's being overidden elsewhere, even though the computed styles reveal no `transition`.)

Removing both `-moz-transform` and `-ms-transform` from either the `-webkit-transition` or `transition` values enables them properly. I suspect that it's considering transform values with properties using unsupported prefixes to be invalid, though I'm not familiar enough with vendor-prefixing to know if this is a common practice.

P.S.: My desktop Safari (9.1), on the other hand, seems fine with the prefixing:
<img width="283" alt="screen shot 2016-05-02 at 10 00 47 am" src="https://cloud.githubusercontent.com/assets/1309177/14961095/c8ec96f6-104c-11e6-9ab7-71d268604e5a.png">

**Comment by rofrischmann** [comment]
It looks like the problem is caused by the following `, 100000ms !important` as it misses a property I guess. The second example (Safari 9.1) seems to have the `opacity` property which is somehow missing above. I act on the assumption that this is not caused by the prefixer as it should return the same values independent of which browser is used.

**Comment by xymostech** [comment]
@rofrischmann You're right, that is very strange! @crm416 can you paste the aphrodite code you used to generate those styles?

**Comment by kentcdodds** [comment]
If we could merge [this](https://github.com/Khan/aphrodite/pull/67) then people could paste their code in the tool and share their jsbin clone :-)

**Comment by kentcdodds** [comment]
😅 nevermind. They'd have to update the bin's initial code (which would be cool too).

Maybe I could enhance the tool to update the URL with the code...

**Comment by kentcdodds** [comment]
The tool's been updated, maybe it'll be helpful :-) https://output.jsbin.com/qoseye

**Comment by crm416** [comment]
Thanks for your response @rofrischmann! Apologies, I must've been testing with a dirty branch when I made that screenshot. Here are the accurate styles on mobile Safari:

<img width="274" alt="screen shot 2016-05-04 at 11 22 05 am" src="https://cloud.githubusercontent.com/assets/1309177/15024670/a39c5c84-11ea-11e6-8372-3ef0f05000ad.png">

(Notice that the `opacity` property is back.)

As an aside, this is also recognized, so I don't think the stray duration on the end is problematic:

<img width="241" alt="screen shot 2016-05-04 at 11 29 59 am" src="https://cloud.githubusercontent.com/assets/1309177/15024879/9b22fae4-11eb-11e6-8f48-923d14525d29.png">

In particular, that style adds an extra `500ms / all` transition:

<img width="242" alt="screen shot 2016-05-04 at 11 30 08 am" src="https://cloud.githubusercontent.com/assets/1309177/15024899/a8737066-11eb-11e6-973d-ccc6a2059ede.png">

For completeness, here's the Aphrodite snippet:

```js
const echoAnimationMs = 100000;
const echoAnimationOffsetY = 50;

const styles = StyleSheet.create({
    enter: {
        opacity: 1,
        transform: 'translateY(0)',
    },

    enterActive: {
        opacity: 0,
        transform: `translateY(-${echoAnimationOffsetY}px)`,
        transition: `transform ${echoAnimationMs}ms, `
            + `opacity ${echoAnimationMs}ms`,
    },
});
```

**Comment by lencioni** [comment]
@crm416 can you try 1.2.0 and let us know if this is still an issue?

**Comment by lencioni** [comment]
Closing this as stale. Please re-open this is still an issue!
