### ISSUE TITLE
CSS rules with semicolons break due to importantify.

### ISSUE THREAD

**Issue by zgotsch** [Khan/aphrodite#70]
We ran into an issue here at Spring when upgrading to the newest version of Aphrodite.

We use inline data uris for image icons, with styles like:

```
cartIcon: {
  backgroundImage: 'url(data:image/svg+xml;base64,PD94...',
  ...
}
```

which produced

```
.cartIcon-somehash {
  background-image: url(data:image/svg+xml !important;base64,...
  ...
}
```

I looked at the code and noticed it would also fail on something like:

```
content: "'my content;'",
```

I have a fix, and will PR.

**Comment by spicyj** [comment]
#29
