### ISSUE TITLE
Support pseudo states with nested children

### ISSUE THREAD

**Issue by viniciusdacal** [Khan/aphrodite#72]
Is there a way to support pseudo state with nested children?
eg.:
```js
button: {
  color: 'white',
  ':hover': {
    color: 'red'
    icon: {
      color: 'inherit'
    }
  }
},
icon: {
  color: 'blue'
}
```

In this case, I need to change my icon color to `inherit` only when button is hovered

**Comment by viniciusdacal** [comment]
Oh, I think there is a pull request opened about this right? #61

**Comment by xymostech** [comment]
That is it! There's also already an issue, #10 which I'm gonna merge this into.
