### ISSUE TITLE
@font-face multiple font styles

### ISSUE THREAD

**Issue by teddybradford** [Khan/aphrodite#80]
I'm trying to figure out how to include 2 font styles for a given font family.

I tried the following, but the `italicFont` *@*font-face isn't being added to the stylesheet.

```js
const font = {
  fontStyle: "normal",
  fontWeight: "normal",
  fontFamily: "My Font",
  src: `url(${myFontWoff}) format("woff"),
        url(${myFontTtf}) format("truetype")`
};

const italicFont = {
  fontStyle: "italic",
  fontWeight: "normal",
  fontFamily: "My Font",
  src: `url(${myItalicFontWoff}) format("woff"),
        url(${myItalicFontTtf}) format("truetype")`
};

fontFamily: [font, italicFont, "serif"]
```

Am I missing something or does this not yet work in Aphrodite?

**Comment by xymostech** [comment]
@teddybradford it's supposed to work! Looks like you're right, this is a bug. Looking at [this example](https://output.jsbin.com/qoseye?code=%7B%0A%20%20%22test%22%3A%20%7B%0A%20%20%20%20fontFamily%3A%20%5B%7B%0A%20%20%20%20%20%20fontStyle%3A%20%22normal%22%2C%0A%20%20%20%20%20%20fontWeight%3A%20%22normal%22%2C%0A%20%20%20%20%20%20fontFamily%3A%20%22My%20Font%22%2C%0A%20%20%20%20%20%20src%3A%20%27url%28blah%29%20format%28%22woff%22%29%2C%20url%28blah%29%20format%28%22truetype%22%29%27%0A%20%20%20%20%7D%2C%20%7B%0A%20%20%20%20%20%20fontStyle%3A%20%22italic%22%2C%0A%20%20%20%20%20%20fontWeight%3A%20%22normal%22%2C%0A%20%20%20%20%20%20fontFamily%3A%20%22My%20Font%22%2C%0A%20%20%20%20%20%20src%3A%20%27url%28blahitalic%29%20format%28%22woff%22%29%2C%20url%28blahitalic%29%20format%28%22truetype%22%29%27%0A%20%20%20%20%7D%5D%0A%20%20%7D%0A%7D) repros it.
