### ISSUE TITLE
Multiple values (prefixes) for "display" property is not valid in chrome

### ISSUE THREAD

**Issue by aliry** [Khan/aphrodite#81]
Don't know if I'm doing something wrong or ...
I have a style with "display: flex" and Aphrodite output look like this:
`display: -webkit-box,-moz-box,-ms-flexbox,-webkit-flex,flex !important` 

which is not working in chrome and marked as invalid property value!

**Comment by xymostech** [comment]
@aliry Hello! What version of aphrodite are you using? I think this was a bug caused by our auto-prefixer in version 0.3.0 that was fixed in 0.3.1.

**Comment by aliry** [comment]
I'm using aphrodite@0.3.1 but it look like version 0.3.1 is not using the latest version of auto-prefixer.
Here is what I get from npm list:
`+-- aphrodite@0.3.1
| `-- inline-style-prefix-all@1.0.5`

**Comment by aliry** [comment]
I think I know what is causing the problem.
The aphrodite version 0.3.1 downloaded from npm is referencing "inline-style-prefix-all": "1.0.5" as dependency.

**Comment by aliry** [comment]
FYI: I've cloned and built locally and it works fine.
I think you should've bump the version with the latest change in package.json (#71)
The one you made to use the latest version of inline-style-prefix-all

**Comment by xymostech** [comment]
It doesn't matter as much whether you're using the lastest version of the auto-prefixer, just that you are using a compatible version of aphrodite and the auto-prefixer!

If I do a clean `npm install aphrodite`, I get the same versions you got, but it generates these styles:

```
.test_poyjc{display:-webkit-box !important;display:-moz-box !important;display:-ms-flexbox !important;display:-webkit-flex !important;display:flex !important;}
```

Can you share a larger example of how you are generating those styles?

**Comment by aliry** [comment]
Thats right it works with a clean install

Thanks
