### ISSUE TITLE
Extending an existing class...

### ISSUE THREAD

**Issue by tracker1** [Khan/aphrodite#84]
I suppose one could export two items...
```
//base
export const base = {...};
export default StyleSheet.create(base);
```

That said, it would be nice to have some sort of way to extend from a base set of styles... so that a deep join could be used on the base styles...

```
//base-style.js
export default StyleSheet.create({
  button: ...
})

//my-component-style.js
import baseStyle from 'base-style.js';

const style = StyleSheet.create({
  button: [
    base.button,
    {
      ...
    }
  ]
});
```

**Comment by kentcdodds** [comment]
I could see this being useful, though I would be hesitant to add it to the core of aphrodite (which is growing in complexity). If it were me, I'd just recommend that if people need to merge styles, just use `Object.assign` or object spread (`...`). If you need a deep merge for some reason, then bring in [`lodash.merge`](http://npm.im/lodash.merge) and use that.

**Comment by jlfwong** [comment]
Thanks for the suggestion!

At the moment, I agree with @kentcdodds. As far as I can tell, this serves as syntactic sugar which can be accomplished with no modification to Aphrodite's core. In the interest in keeping the core small (both in terms of complexity and in terms of bytes-your-users-pay-for), I'm going to close this.

If I'm misunderstanding your suggestion, or you have a compelling reason for this to become part of the core, please let me know!
