### ISSUE TITLE
Make a separate dev build to provide useful warning messages

### ISSUE THREAD

**Issue by jlfwong** [Khan/aphrodite#88]
I'd like to include warning messages for improper usage of aphrodite, but don't want it to bloat production build sizes.

This would be useful for e.g. discouraging the following hack once we have a proper solution (described in #10)

```
const styles = StyleSheet.create({
  parent: {
    ':hover .child': {
      backgroundColor: blue
    }
  }
});
```

**Comment by kevinbarabash** [comment]
It would also be nice to validate values , e.g. `display: 'inline-blick'` should cause a warning in dev.  Obviously some props are easier to validate than others.

**Comment by xymostech** [comment]
> It would also be nice to validate values , e.g. display: 'inline-blick'

With the goal of not including a CSS parser in aphrodite, I'd be against this sort of validation. We'd also start yelling at people about new CSS standards (who is to say that `"inline-blick"` won't be the new hotness in the future?!)

**Comment by kevinbarabash** [comment]
@xymostech you're probably right... I guess I miss the validation my editor usually gives me in .css/.less files.  Maybe someone will build a separate thing for validating aphrodite styles at compile/lint time.

**Comment by kentcdodds** [comment]
Could make an eslint plugin. That'd be pretty awesome

**Comment by lencioni** [comment]
While I think there is probably room for better error messages in dev, this issue isn't very actionable so I'm going to close it. If you disagree, please open a new issue with a more actionable proposal!
