### ISSUE TITLE
Use CRC32 instead of counter to de-dup styles

### ISSUE THREAD

**Issue by jlfwong** [Khan/aphrodite#9]
We currently generate monotonically increasing IDs to differentiate multiple styles with the same name, which isn't going to work for server-side rehydration.

One idea is to take the CRC32 of the `JSON.stringify` of the style definition, then append that to the style name (or possibly even use that as the entire style name -- something like `s${base58(crc(JSON.stringify(styleDefinition)))`

Base 58: https://en.wikipedia.org/wiki/Base58
Small JS CRC implementation: http://stackoverflow.com/a/18639999

**Comment by jlfwong** [comment]
Hmm, I guess `JSON.stringify` isn't guaranteed to produce the same results on the server and client, so this might be a non-starter. We could code our own stable stringify function for our styles, perhaps?

**Comment by spicyj** [comment]
It isn't?

**Comment by jlfwong** [comment]
@spicyj From (minimal) searching, I couldn't find anything providing a guarantee about character-for-character output matching for `JSON.stringify` between browsers, but maybe it does. If it does, great!

**Comment by spicyj** [comment]
The ES6 spec (and I assume, ES5 too) specifies the exact behavior, like almost everything in JS.

**Comment by xymostech** [comment]
This sounds excellent! This would also have the benefit of deduplicating styles that occur over different files but look the same (which I'm sure we're going to end up having all over the place).

It'd be nice to also think about how we want to do minification. It'd be nice if we could map from the really long concatenated names to something much shorter. That might require an extra step for rehydration (like passing a map of long name -> short name form the server to the client version of aphrodite).

**Comment by xymostech** [comment]
Fixed by f45f87d25f53644
