### ISSUE TITLE
Support props argument for StyleSheet.create

### ISSUE THREAD

**Issue by kentcdodds** [Khan/aphrodite#98]
Inspired by @rofrischmann's [fela](https://github.com/rofrischmann/fela/). It appears to be a pretty slick API. Something like:

```javascript
StyleSheet.create(props => ({
  bar: {
    fontSize: props.big ? '25px' : '15px',
    // etc.
  }
}))
```

**Comment by jlfwong** [comment]
I think this is syntactic sugar. Just use functions:

```
const styles = (props) => StyleSheet.create({
    bar: {
        fontSize: props.big ? '25px' : '15px'
    }
});
```

Then use as `styles({big: true}).bar`. Could be memoized appropriately.

So it may indeed be useful syntactic sugar, but IMO, does not belong in Aphrodite core.

**Comment by bkgunby** [comment]
Is it not recommended to call `StyleSheet.create()` within the render function?

**Comment by kentcdodds** [comment]
If you need to, then it's never been a problem for me.

**Comment by devDanielCespedes** [comment]
Thanks aloooot @jlfwong

> I think this is syntactic sugar. Just use functions:
> 
> ```
> const styles = (props) => StyleSheet.create({
>     bar: {
>         fontSize: props.big ? '25px' : '15px'
>     }
> });
> ```
> 
> Then use as `styles({big: true}).bar`. Could be memoized appropriately.
> 
> So it may indeed be useful syntactic sugar, but IMO, does not belong in Aphrodite core.
